### ISSUE TITLE
(ProfitTrailer-Feeder-Tools) Backup and Auto Restart - Error: Windows cannot find ProfitTrailer.cmd

### ISSUE THREAD

**Issue by orionmodern** [CryptoGnome/Community-Tools#13]
Hello, I tried to use this tool and I'm getting the error "Windows cannot find "ProfitTrailer.cmd". Make sure you type the name correctly, and then try again."﻿

I'm using the latest version of PT and PTF

**Comment by Imotheb** [comment]
Try RUN-ProfitTrailer.cmd
