### ISSUE TITLE
3 Prices seem to be stagnant... did the bot hang? popps up every 10 seconds

### ISSUE THREAD

**Issue by atka007** [CryptoGnome/Community-Tools#14]
Just updated to latest script. I am getting this error message every 10 seconds:
3 Prices seem to be stagnant... did the bot hang?
I am using PT 16 with Feeder on Binance .
The graphs seem to update. I have some pretty deep bags.

BTW love the TradingView link icons.

**Comment by JoseAntonioCaraballo** [comment]
Did you resolve this? Im having the same problem.

**Comment by valentinmuller** [comment]
I'd wish to know as well.

**Comment by JoseAntonioCaraballo** [comment]
I resolved this I ended up disableing it
Okay go to the exstention that you downloaded to paste the code(It should be named "CJS" in top right)
when you see the code you pasted go to line where it says

"util.testHangWarning = false; // --- true to enable hang warnings; false to disable"

mine is line 27. Change that from true to false and save. This should stop it.

**Comment by JoseAntonioCaraballo** [comment]
Tell me if it worked

**Comment by valentinmuller** [comment]
It worked. Cheers

**Comment by JoseAntonioCaraballo** [comment]
cheers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
