### ISSUE TITLE
Web-GUI-Addons Doesn't Work for USDT

### ISSUE THREAD

**Issue by tooraj-enayati** [CryptoGnome/Community-Tools#3]
I use teh bot for trading in USDT  and the Web-GUI-Addons assumes all the values are in BTC, not USDT so I get some funky numbers! :)

Maybe the script can ignore the values if in USDT as they are already in USD. But I suspect the problem be worse if someone trades in ETH.

![capture](https://user-images.githubusercontent.com/24386973/35463497-0bd38848-0345-11e8-8047-9be1b4823896.JPG)

**Comment by clownfish44** [comment]
ETH and BTC work please do not use USDT it is a scam. Please google tether coin news
