### ISSUE TITLE
Use a lot of SSD space from VPS.

### ISSUE THREAD

**Issue by Cryptomi** [CryptoGnome/Community-Tools#4]
i like the tool, but they use to much ssd space on vps from backup every 10min.
Is it possible to let the bot delete the last backup when create a new one ? 
Or maybe just backup once a day, ore just safe last 5 backups and delete rest ?
It will help a lot :)

**Comment by clownfish44** [comment]
No it does not use alot of space it only backup's the settings which is less than 10kb per backup if your haven't updated you need to.
